INSERT INTO `award`.`customer` (`id`, `name`) VALUES ('1', 'Jhon');
INSERT INTO `award`.`customer` (`id`, `name`) VALUES ('2', 'Anderson');
INSERT INTO `award`.`customer` (`id`, `name`) VALUES ('3', 'James');
INSERT INTO `award`.`customer` (`id`, `name`) VALUES ('4', 'Steve');
INSERT INTO `award`.`customer` (`id`, `name`) VALUES ('5', 'Peter');
INSERT INTO `award`.`customer` (`id`, `name`) VALUES ('6', 'Nicole');
INSERT INTO `award`.`customer` (`id`, `name`) VALUES ('7', 'Wendy');
INSERT INTO `award`.`customer` (`id`, `name`) VALUES ('8', 'Josh');

INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('1', '1', '200', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('2', '1', '70', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('3', '1', '20', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('4', '1', '200', '2021-01-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('5', '1', '200000.10', '2021-01-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('6', '2', '3000', '2021-07-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('7', '2', '210', '2021-1-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('8', '3', '210', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('9', '3', '210', '2021-12-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('10', '3', '210', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('11', '4', '1.8', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('12', '4', '210', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('13', '4', '99.99', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('14', '4', '101', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('15', '5', '51', '2021-07-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('16', '5', '51.0', '2021-07-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('17', '5', '49', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('18', '6', '49', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('19', '6', '49.9', '2021-11-05');
INSERT INTO `award`.`transaction` (`id`, `customer_id`, `cost`, `date`) VALUES ('20', '7', '1', '2021-11-05');